blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Beta/Alpha Testing Program (EzL)
    url: https:://ezsys.link/labs
    about: This is the place where you can test new features and access the contributor chat.
  - name: â“ Support & Suggestions - Official Discord Server
    url: https://ezsys.link/support
    about: This is the appropriate place to contact us with your inquiries, engage in conversation with other members of the community, propose new ideas, and report any (technical) issues you may encounter.
